"""Update table history

Revision ID: 285d13267b39
Revises: 7062fd9585a2
Create Date: 2025-08-03 17:16:30.932605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '285d13267b39'
down_revision: Union[str, Sequence[str], None] = '7062fd9585a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('History', sa.Column('prompt_text', sa.String(), nullable=False))
    op.add_column('History', sa.Column('num_images', sa.Integer(), nullable=True))
    op.add_column('History', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('History', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('History', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('History', 'created_at')
    op.drop_column('History', 'num_images')
    op.drop_column('History', 'prompt_text')
    # ### end Alembic commands ###
